### ISSUE TITLE
Vaadin 25: cannot compile with 25.0.0-beta7

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/GridHelpers#150]
### Describe the bug

error: com.flowingcode.vaadin.addons.gridhelpers.HeaderFooterStylesHelper.ClassListImpl is not abstract and does not override abstract method bind(java.lang.String,com.vaadin.signals.Signal<java.lang.Boolean>) in com.vaadin.flow.dom.ClassList

### Expected behavior

Compilation must not fail

### Minimal reproducible example

mvn compile -Pv25

### Add-on Version

1.5.0-SNAPSHOT

### Vaadin Version

25.0.0-beta7

**Comment by javier-godoy** [comment]
This is no longer an issue after https://github.com/vaadin/flow/pull/22939 in 25.0.0-rc1
